version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1


  apache: 
    image: httpd:latest 
    restart: always 
    ports: 
      - 8080:80
    volumes: 
      - "C:/Admin/Documents/htdocs":/user/local/apache2/htdocs 